// This file is generated from Rust API response/request types.
// Run `pnpm generate:api-contract` from web/ to update it.
// Do not edit this file by hand.

export type ErrorCode = "attachment_upload_expired" | "bad_request" | "cli_upgrade_required" | "conflict" | "forbidden" | "internal" | "not_found" | "payload_too_large" | "protected_path" | "range_not_satisfiable" | "request_timeout" | "service_unavailable" | "shared_repositories" | "too_many_requests" | "unauthorized";

export type ErrorFields = { paths?: Array<string>, installed_protocol?: number | null, supported_protocol?: number | null, 
/**
 * Repository ids, as `owner/name`, that the error is about.
 */
repositories?: Array<string>, };

export type ErrorResponse = { code: ErrorCode, message: string, error_reference?: string | null, instruction?: string | null, fields?: ErrorFields, retryable: boolean, };

export type ViewId = string;

export type RepositoryActor = "Public" | "Member" | "Owner";

export type RepositoryMemberPermissions = { can_push: boolean, can_change_file_visibility: boolean, view: ViewId, };

export type RepositoryInviteState = "Pending" | "Accepted" | "Revoked" | "Expired";

export type RepoLifecycleState = "AwaitingFirstPush" | "Ready";

export type RepoChangeEvent = { repo_id: string, incarnation_id: string, version: number, kind: RepoChangeKind, };

export type RepositoryDependencyCheckStatus = "Pending" | "Ready" | "Updating" | "Failed" | "Unsupported";

export type RepositoryDependencyGapResponse = { path: string, reason: string, };

export type RepositoryDependencyFindingResponse = { source_path: string, target_path: string, };

export type RepositoryDependencyReportResponse = { commit_oid: string, analyzer_version: string, analyzed_file_count: number, unsupported_files: Array<string>, gaps: Array<RepositoryDependencyGapResponse>, findings: Array<RepositoryDependencyFindingResponse>, public_file_count: number, };

export type RepositoryDependencyCheckResponse = { status: RepositoryDependencyCheckStatus, report: RepositoryDependencyReportResponse | null, error: string | null, };

export type FirstPushTokenStatus = "Active" | "Expired" | "Used";

export type FileChangeKind = "Added" | "Modified" | "Deleted";

export type RepoConfig = { kind: string, version: number, views: Array<ViewDefinition>, files: RepoConfigFiles, history: RepoConfigHistory, };

export type ViewDefinition = { id: ViewId, name: string, includes: ViewIncludes, readers: ViewReaders, };

export type ViewIncludes = string | Array<ViewId>;

export type ViewReaders = "anyone" | "assigned";

export type ViewsTransition = { before: Array<ViewDefinition>, after: Array<ViewDefinition>, };

export type RepoConfigFiles = { default: ViewId, rules: Array<RepoConfigFileRule>, };

export type RepoConfigFileRule = { path: string, view: ViewId, };

export type RepoConfigHistory = { rewrites: Array<HistoryRewriteRequest>, };

export type HistoryRewriteRequest = { path: string, action: HistoryRewriteAction, };

export type HistoryRewriteAction = "redact-public-history";

export type RequestActorRole = "Public" | "Member" | "Owner";

export type RequestState = "Draft" | "Open" | "Closed" | "Merged";

export type RequestAttachmentTargetKind = "Description" | "Discussion" | "Reply";

export type RequestAttachmentTargetInput = { kind: RequestAttachmentTargetKind, discussion_id: string | null, };

export type RequestAttachmentKind = "Photo" | "Video";

export type RequestAttachmentState = "Prepared" | "Uploaded" | "Processing" | "Ready" | "Failed" | "Rejected";

export type RequestAttachmentDerivativeKind = "ImagePreview" | "VideoPlayback" | "VideoPoster";

export type RequestAttachmentFailureCode = "InvalidMedia" | "CorruptMedia" | "UnsupportedMedia" | "MediaLimitExceeded" | "CodecFailed" | "StorageUnavailable" | "Internal";

export type RequestAttachmentLimitsResponse = { accepted_photo_media_types: Array<string>, accepted_video_media_types: Array<string>, max_photo_bytes: number, max_video_bytes: number, max_video_duration_seconds: number, max_attachments_per_content: number, max_request_source_bytes: number, max_repository_storage_bytes: number, max_photo_pixels: number, preferred_part_bytes: number, max_concurrent_parts: number, incomplete_upload_ttl_seconds: number, unbound_attachment_ttl_seconds: number, };

export type PrepareRequestAttachmentRequest = { operation_id: string, target: RequestAttachmentTargetInput, filename: string, declared_media_type: string, size_bytes: number, sha256: string, };

export type PrepareRequestAttachmentResponse = { attachment: RequestAttachmentResponse, transfer: RequestAttachmentTransferResponse, };

export type RequestAttachmentTransferResponse = { upload_id: string, media_base_url: string, grant: string, expires_at_unix: number, preferred_part_bytes: number, max_concurrent_parts: number, acknowledged_parts: Array<RequestAttachmentPartReceiptResponse>, };

export type RequestAttachmentPartReceiptResponse = { part_number: number, size_bytes: number, sha256: string, };

export type FinishRequestAttachmentRequest = { upload_id: string, parts: Array<RequestAttachmentPartReceiptResponse>, };

export type RetryRequestAttachmentRequest = { operation_id: string, };

export type RequestAttachmentListResponse = { attachments: Array<RequestAttachmentResponse>, };

export type RequestAttachmentResponse = { id: string, request_id: string, uploader_user_id: string, filename: string, declared_media_type: string, detected_media_type: string | null, kind: RequestAttachmentKind, size_bytes: number, sha256: string, state: RequestAttachmentState, original_download_available: boolean, failure: RequestAttachmentFailureResponse | null, image: RequestAttachmentImageMetadataResponse | null, video: RequestAttachmentVideoMetadataResponse | null, derivatives: Array<RequestAttachmentDerivativeResponse>, created_at_unix: number, updated_at_unix: number, };

export type RequestAttachmentImageMetadataResponse = { width: number, height: number, };

export type RequestAttachmentVideoMetadataResponse = { width: number, height: number, duration_millis: number, };

export type RequestAttachmentDerivativeResponse = { id: string, kind: RequestAttachmentDerivativeKind, media_type: string, size_bytes: number, width: number | null, height: number | null, duration_millis: number | null, };

export type RequestAttachmentFailureResponse = { code: RequestAttachmentFailureCode, message: string, retryable: boolean, };

export type RequestAttachmentMediaTarget = { "kind": "original" } | { "kind": "derivative", derivative_id: string, };

export type CreateRequestAttachmentMediaGrantRequest = { target: RequestAttachmentMediaTarget, };

export type CreateRequestAttachmentMediaGrantResponse = { media_url: string, grant: string, expires_at_unix: number, };

export type RequestAttachmentMediaGrantClaims = { attachment_id: string, repository_id: string, request_id: string, viewer_user_id: string | null, target: RequestAttachmentMediaTarget, expires_at_unix: number, };

export type RequestAttachmentUploadGrantClaims = { attachment_id: string, repository_id: string, request_id: string, uploader_user_id: string, upload_id: string, expires_at_unix: number, };

export type GitOid = string;

export type RequestEventKind = "Started" | "Submitted" | "RevisionPushed" | "Merged" | "Closed" | "IdentityEdited" | "DiscussionResolved" | "DiscussionReopened" | "AutoMergeEnabled" | "AutoMergeCancelled" | "AutoMergeStopped" | "AutoMergeFulfilled";

export type AccountSessionResponse = { identity: SessionIdentity | null, user: UserResponse | null, };

export type UserResponse = { id: string, handle: string, email: string, email_verified: boolean, };

export type SessionIdentity = { user_id: string, email: string | null, email_verified: boolean, };

export type DeviceLoginStatus = "Pending" | "Complete";

export type DeviceLoginStartResponse = { device_code: string, user_code: string, verification_url: string, expires_at_unix: number, poll_interval_secs: number, };

export type DeviceLoginPollResponse = { status: DeviceLoginStatus, session_token: string | null, expires_at_unix: number, identity: SessionIdentity | null, };

export type DeviceLoginCompleteResponse = { status: DeviceLoginStatus, };

export type BrowserLoginStartRequest = { callback_url: string, };

export type BrowserLoginStartResponse = { request_id: string, request_secret: string, authorization_url: string, expires_at_unix: number, };

export type BrowserLoginCompleteResponse = { callback_url: string, };

export type BrowserLoginExchangeRequest = { request_secret: string, callback_code: string, };

export type CliSessionTokenResponse = { session_token: string, expires_at_unix: number, identity: SessionIdentity, };

export type CliExchangeGrantResponse = { exchange_token: string, expires_at_unix: number, };

export type CliExchangeGrantExchangeRequest = { exchange_token: string, };

export type CliSessionsResponse = { sessions: Array<CliSessionResponse>, };

export type CliSessionResponse = { id: string, label: string, created_at_unix: number, last_used_at_unix: number | null, expires_at_unix: number, };

export type RepoSummaryResponse = { description: string | null, website_url: string | null, id: string, owner_handle: string, name: string, git_remote_url: string, lifecycle_state: RepoLifecycleState, change_version: number, content_version: number, access: RepositoryAccessResponse, views: Array<ViewDefinition>, open_request_count: number, };

export type OwnerProfileResponse = { handle: string, repositories: Array<RepoSummaryResponse>, };

export type CreateRepoRequest = { name: string, file_default_view: ViewId | null, };

export type UpdateRepoMetadataRequest = { description: string | null, website_url: string | null, };

export type CreateRepoResponse = { repo: RepoSummaryResponse, init: RepoInitResponse, };

export type DeleteRepoResponse = { id: string, deleted: boolean, };

export type CreatePushIntentRequest = { head_oid: string, base_config_hash: string, config: RepoConfig, };

export type CreatePushIntentResponse = { token: string, base_head_oid: GitOid | null, expires_at_unix: number, };

export type RepoInitResponse = { repo: RepoSummaryResponse, git_remote_url: string, remote_name: string, push_branch: string, token: FirstPushTokenResponse | null, push_token: GitPushTokenResponse | null, };

export type RepoConfigResponse = { config: RepoConfig, config_hash: string, lifecycle_state: RepoLifecycleState, access: RepositoryAccessResponse, head_oid: string | null, };

export type FirstPushTokenResponse = { status: FirstPushTokenStatus, created_at_unix: number, expires_at_unix: number, used_at_unix: number | null, secret: string | null, };

export type GitPushTokenResponse = { created_at_unix: number, secret: string | null, };

export type RepoFileResponse = { path: string, oid: string, tracked: boolean, label: ViewId, };

export type RepoFileContentRequest = { path: string, };

export type RepoFileContentResponse = { path: string, oid: string, label: ViewId, size_bytes: number, content: ReviewFileContentResponse, };

export type RepositoryAccessResponse = { actor: RepositoryActor, view: ViewId, can_push: boolean, can_change_file_visibility: boolean, can_manage_members: boolean, can_delete_repo: boolean, };

export type RepositoryCollaborationResponse = { members: Array<RepositoryMemberResponse>, invites: Array<RepositoryInviteResponse>, };

export type RepositoryMemberResponse = { user_id: string, handle: string, email: string, permissions: RepositoryMemberPermissions, created_at_unix: number, updated_at_unix: number, };

export type RepositoryInviteResponse = { id: string, invited_email: string, permissions: RepositoryMemberPermissions, state: RepositoryInviteState, expires_at_unix: number, 
/**
 * The newest email for this invite. `None` when it was never emailed.
 */
email: RepositoryInviteEmailResponse | null, };

export type RepositoryInviteEmailResponse = { state: RepositoryInviteEmailStateResponse, requested_at_unix: number, };

export type RepositoryInviteEmailStateResponse = "queued" | "sent" | "failed";

export type CreateRepositoryInviteRequest = { email: string, permissions: RepositoryMemberPermissions, };

export type UpdateRepositoryMemberRequest = { permissions: RepositoryMemberPermissions, };

export type RepositoryInviteLinkResponse = { invite_url: string, };

export type RepositoryInviteLandingResponse = { "status": "open", viewer: RepositoryInviteViewerResponse, viewer_email: string | null, owner_handle: string, repo_name: string, invited_email: string, permissions: RepositoryMemberPermissions, expires_at_unix: number, } | { "status": "member", owner_handle: string, repo_name: string, } | { "status": "expired", owner_handle: string, repo_name: string, } | { "status": "revoked" } | { "status": "access_removed" } | { "status": "used" } | { "status": "invalid" };

export type RepositoryInviteViewerResponse = "ready" | "signed_out" | "wrong_account" | "email_unverified";

export type AcceptRepositoryInviteResponse = { repo: RepoSummaryResponse, member: RepositoryMemberResponse, };

export type GitHubConnectionResponse = { 
/**
 * `false` when this server has no GitHub App, so nothing can connect.
 */
configured: boolean, connection: GitHubConnectionDetailsResponse | null, 
/**
 * The check names GitHub must pass before a request merges.
 */
required_checks: Array<string>, 
/**
 * Whether the viewer may confirm that a public GitHub repository
 * receives what Scope pushes, private requests included.
 */
can_confirm_public: boolean, 
/**
 * The latest connection test, while the repository has a link.
 */
setup_check: GitHubSetupCheckResponse | null, 
/**
 * How many of GitHub's most recent workflow runs connecting imports.
 */
run_import_count: number, 
/**
 * The latest import of the linked GitHub repository's runs.
 */
run_import: GitHubRunImportResponse | null, };

export type GitHubConnectionDetailsResponse = { github_full_name: string, github_url: string, 
/**
 * `None` once that account was deleted.
 */
connected_by: RequestActorSummaryResponse | null, connected_at_unix: number, 
/**
 * Set when GitHub took the repository away from Scope.
 */
disconnected: GitHubDisconnectionResponse | null, 
/**
 * Everything Scope pushes to a public GitHub repository is public.
 */
public_on_github: boolean, 
/**
 * False while a repository that became public waits for a maintainer to
 * confirm; private requests are not sent there meanwhile.
 */
public_confirmed: boolean, };

export type GitHubDisconnectionResponse = { reason: GitHubDisconnectReasonResponse, at_unix: number, };

export type GitHubDisconnectReasonResponse = "app_uninstalled" | "installation_suspended" | "repository_removed";

export type GitHubAuthorizeRequest = { 
/**
 * The origin of the page that started connecting. GitHub returns there
 * when it is an allowed Scope web origin, so a development stack reached
 * at another address works. Without it, the public app origin is used.
 */
web_origin: string | null, };

export type GitHubAuthorizeResponse = { authorize_url: string, };

export type GitHubSetupRequest = { state: string, code: string, };

export type GitHubSetupResponse = { owner_handle: string, repo_name: string, repositories: Array<GitHubRepositoryResponse>, 
/**
 * Where to install the app on a repository that is missing.
 */
install_url: string, grant: string, 
/**
 * How many recent workflow runs the repository imports, which
 * connecting can change.
 */
run_import_count: number, };

export type GitHubRepositoryResponse = { id: number, full_name: string, private: boolean, };

export type ConnectGitHubRepositoryRequest = { grant: string, github_repository_id: number, 
/**
 * Required for a public GitHub repository: everything Scope pushes there,
 * private requests and private files included, becomes public.
 */
acknowledge_public: boolean, 
/**
 * How many of GitHub's most recent workflow runs to import, which
 * becomes the repository's import count.
 */
run_import_count: number, };

export type SetGitHubRequiredChecksRequest = { names: Array<string>, };

export type SetGitHubRunImportCountRequest = { count: number, };

export type GitHubRunImportStateResponse = "queued" | "running" | "succeeded" | "failed";

export type GitHubRunImportResponse = { state: GitHubRunImportStateResponse, 
/**
 * The most runs it reads.
 */
run_count: number, 
/**
 * How many runs it stored, once it succeeded.
 */
imported_count: number, 
/**
 * What GitHub answered when the latest attempt failed. A queued import
 * with an error tries again.
 */
error: string | null, queued_at_unix: number, finished_at_unix: number | null, };

export type GitHubSetupCheckStateResponse = "pushing" | "waiting" | "finished" | "failed";

export type GitHubSetupCheckResponse = { branch: string, commit_oid: string, state: GitHubSetupCheckStateResponse, started_at_unix: number, finished_at_unix: number | null, 
/**
 * The check names GitHub reported for the test, which can be required.
 */
check_names: Array<string>, 
/**
 * GitHub's answer to a refused push, or why no workflow started.
 */
message: string | null, };

export type GitHubWorkflowRunsResponse = { 
/**
 * Whether this server can connect repositories to GitHub at all.
 */
configured: boolean, 
/**
 * `None` when the repository is not linked to GitHub; its runs are Scope's own.
 */
github: GitHubWorkflowRunListResponse | null, };

export type GitHubWorkflowRunListResponse = { 
/**
 * The repository's Actions page, which has every run and its logs.
 */
actions_url: string, 
/**
 * A page of runs, newest first.
 */
workflow_runs: Array<GitHubWorkflowRunResponse>, 
/**
 * The names of the workflows with stored runs, which the list can be
 * narrowed to.
 */
workflows: Array<string>, 
/**
 * Continues the list after this page, while there is more.
 */
next_cursor: string | null, };

export type GitHubWorkflowRunResponse = { id: number, workflow_name: string, branch: string | null, head_oid: string, event: string, status: GitHubCheckStatus, conclusion: GitHubCheckConclusion | null, html_url: string, run_started_at_unix: number | null, updated_at_unix: number, 
/**
 * The Scope request whose branch the run is on.
 */
request_id: string | null, };

export type GitHubWorkflowRunDetailResponse = { run: GitHubWorkflowRunResponse, 
/**
 * In the order GitHub created them.
 */
jobs: Array<GitHubWorkflowJobResponse>, 
/**
 * Set when Scope has no jobs for the run because GitHub could not be read.
 */
jobs_unavailable: string | null, };

export type GitHubWorkflowJobResponse = { id: number, name: string, status: GitHubCheckStatus, conclusion: GitHubCheckConclusion | null, started_at_unix: number | null, completed_at_unix: number | null, 
/**
 * The job on GitHub, which keeps its whole log.
 */
html_url: string, steps: Array<GitHubWorkflowStepResponse>, };

export type GitHubWorkflowStepResponse = { number: number, name: string, status: GitHubCheckStatus, conclusion: GitHubCheckConclusion | null, started_at_unix: number | null, completed_at_unix: number | null, };

export type GitHubWorkflowJobLogResponse = { 
/**
 * `None` when GitHub no longer keeps the log.
 */
text: string | null, 
/**
 * Whether `text` is only the end of a longer log.
 */
truncated: boolean, };

export type HistoryPageRequest = { feed: HistoryFeed | null, view: ViewId | null, before: string | null, };

export type HistoryEntryRequest = { view: ViewId | null, };

export type HistoryEntryFileDiffRequest = { commit_oid: string | null, visibility_change: string | null, view: ViewId | null, path: string, };

export type RequestFileDiffRequest = { path: string, };

export type ReviewFileContentResponse = { "kind": "text", text: string, } | { "kind": "binary", oid: string, size_bytes: number, };

export type ReviewFileDiffResponse = { path: string, kind: FileChangeKind, old_mode: string | null, new_mode: string | null, old_content: ReviewFileContentResponse | null, new_content: ReviewFileContentResponse | null, };

export type HistoryPageResponse = { feed: HistoryFeed, view: ViewId, repo_id: string, generation: string, head_oid: string | null, entries: Array<HistoryEntrySummaryResponse>, next_cursor: string | null, };

export type HistoryEntrySummaryResponse = { occurred_at_unix: number | null, id: string, source_id: string, parent_id: string | null, kind: HistoryEntryKind, author: string | null, message: string, file_change_count: number, visibility_summary: HistoryVisibilitySummaryResponse, views: ViewsTransition | null, };

export type HistoryEntryKind = "push" | "merged_request" | "visibility_change" | "views_change";

export type HistoryFeed = "updates" | "all" | "visibility";

export type HistoryEntryDetailResponse = { native_commits: Array<NativeHistoryCommitResponse>, view: ViewId, repo_id: string, occurred_at_unix: number | null, id: string, source_id: string, 
/**
 * Adjacent entries in all activity, addressed by source id.
 */
older_source_id: string | null, newer_source_id: string | null, kind: HistoryEntryKind, author: string | null, message: string, file_change_count: number, visibility_summary: HistoryVisibilitySummaryResponse, files: Array<HistoryEntryFileResponse>, visibility_changes: Array<HistoryVisibilityChangeResponse>, views: ViewsTransition | null, };

export type HistoryEntryFileResponse = { path: string, kind: FileChangeKind, old_mode: string | null, new_mode: string | null, old_oid: string | null, new_oid: string | null, label: ViewId, };

export type NativeHistoryCommitResponse = { oid: string, parent_oids: Array<string>, tree_oid: string, author: string, message: string, occurred_at_unix: number, files: Array<HistoryEntryFileResponse>, };

export type HistoryVisibilitySummaryResponse = { entered_count: number, left_count: number, };

export type HistoryVisibilityChangeResponse = { id: string, file: HistoryEntryFileResponse | null, path: string, old_label: ViewId, new_label: ViewId, };

export type CommitFileResponse = { path: string, kind: FileChangeKind, old_mode: string | null, new_mode: string | null, old_oid: string | null, new_oid: string | null, label: ViewId, };

export type ProjectionPreviewRequest = { view: ViewId, };

export type ProjectionPreviewResponse = { view: ViewId, repo_id: string, head_oid: string | null, files: Array<ProjectionPreviewFileResponse>, commits: Array<ProjectionPreviewCommitResponse>, summary: ProjectionPreviewSummaryResponse, };

export type ProjectionPreviewFileResponse = { path: string, oid: string, label: ViewId, };

export type ProjectionPreviewCommitResponse = { projected_id: string, logical_commit_id: string, parent_projected_ids: Array<string>, author: string | null, message: string, visibility: ProjectionPreviewCommitVisibilityResponse, change_count: number, };

export type ProjectionPreviewCommitVisibilityResponse = "AllInView" | "SomeInView" | "NoneInView";

export type ProjectionPreviewSummaryResponse = { visible_files: number, hidden_files: number, visible_commits: number, hidden_commits: number, };

export type RequestQueueSection = "active" | "unclaimed" | "set_aside" | "done";

export type RequestQueueGroup = "needs_you" | "waiting" | "unclaimed" | "set_aside" | "done";

export type RequestAttentionState = "active" | "waiting" | "snoozed" | "settled";

export type RequestAttentionReason = "authored" | "invited" | "claimed" | "unclaimed" | "claimed_elsewhere" | "new_activity" | "restored" | "snooze_expired" | "waiting" | "snoozed" | "settled" | "open" | "closed" | "merged";

export type RequestAttentionResponse = { 
/**
 * The group this row shows in for its viewer.
 */
group: RequestQueueGroup, state: RequestAttentionState, reason: RequestAttentionReason, activity_version: number, through_activity_version: number, snoozed_until_unix: number | null, 
/**
 * Counts the writes to the viewer's attention record; zero without one.
 */
revision: number, can_claim: boolean, can_set_aside: boolean, can_restore: boolean, can_release: boolean, };

export type RequestAttentionActionRequest = { "action": "claim", expected_activity_version: number, } | { "action": "wait", expected_activity_version: number, } | { "action": "settle", expected_activity_version: number, } | { "action": "snooze", expected_activity_version: number, until_unix: number, } | { "action": "restore", expected_activity_version: number, } | { "action": "release", expected_activity_version: number, };

export type RequestAttentionMutationResponse = { attention: RequestAttentionResponse, claimer: RequestActorSummaryResponse | null, };

export type RequestQueueItemResponse = { attention_at_unix: number, request: RequestListItemResponse, 
/**
 * Null once that account is deleted; clients show a deleted user.
 */
author: RequestActorSummaryResponse | null, attention: RequestAttentionResponse, claimer: RequestActorSummaryResponse | null, };

export type RequestQueuePageResponse = { requests: Array<RequestQueueItemResponse>, next_cursor: string | null, next_attention_at_unix: number | null, };

export type RequestListResponse = { requests: Array<RequestListItemResponse>, next_cursor: string | null, };

export type RequestDetailResponse = { request: RequestSummaryResponse, };

export type CreateRequestRatingRequest = { score: number, reason: string, };

export type RequestRatingParticipantResponse = { id: string, handle: string, rating_score_sum: number, rating_count: number, };

export type RequestRatingResponse = { id: string, request_id: string, rater: RequestRatingParticipantResponse, subject: RequestRatingParticipantResponse, score: number, reason: string, created_at_unix: number, };

export type RequestRatingsResponse = { ratings: Array<RequestRatingResponse>, eligible_subject: RequestRatingParticipantResponse | null, };

export type RequestMutationResponse = { request: RequestSummaryResponse, };

export type RequestListItemResponse = { id: string, name: string, title: string, author_role: RequestActorRole, view: ViewId, head_oid: GitOid, state: RequestState, submitted_at_unix: number | null, updated_at_unix: number, mergeability: RequestMergeabilityResponse, };

export type RequestSummaryResponse = { id: string, name: string, title: string, description_markdown: string, 
/**
 * Null once that account is deleted; clients show a deleted user.
 */
author_user_id: string | null, author_role: RequestActorRole, view: ViewId, base_main_oid: GitOid, head_oid: GitOid, state: RequestState, activity_version: number, submitted_at_unix: number | null, closed_at_unix: number | null, closed_by_user_id: string | null, merged_at_unix: number | null, merged_by_user_id: string | null, merged_head_oid: GitOid | null, merged_main_oid: GitOid | null, created_at_unix: number, updated_at_unix: number, invitees: Array<RequestInviteeResponse>, permissions: RequestPermissionsResponse, mergeability: RequestMergeabilityResponse, };

export type RequestInviteeResponse = { user: RequestActorSummaryResponse, 
/**
 * Null once that account is deleted; clients show a deleted user.
 */
invited_by_user_id: string | null, created_at_unix: number, };

export type AddRequestInviteeRequest = { handle: string, };

export type RemoveRequestInviteeRequest = { handle: string, };

export type RequestInviteeMutationResponse = { request: RequestSummaryResponse, invitee: RequestInviteeResponse, };

export type LeaveRequestResponse = { invitee: RequestInviteeResponse, };

export type RequestPermissionsResponse = { can_view_activity: boolean, can_open_discussion: boolean, can_reply_to_discussion: boolean, can_wait_after_reply: boolean, can_edit_identity: boolean, can_pull_branch: boolean, can_push_branch: boolean, can_submit: boolean, can_manage_invitees: boolean, can_leave_request: boolean, can_close: boolean, can_merge: boolean, };

export type RequestMergeabilityStatus = "Ready" | "Draft" | "Closed" | "Merged" | "NotMaintainer" | "MissingRequestBranch" | "ChecksNotEvaluated" | "ChecksAwaitingApproval" | "ChecksPending" | "ChecksFailed" | "ChecksConfigurationError";

export type RequestMergeabilityResponse = { status: RequestMergeabilityStatus, current_main_oid: GitOid | null, request_head_oid: GitOid, reason: string | null, };

export type RequestCheckEvaluationState = "no-checks" | "awaiting-approval" | "started" | "configuration-error";

export type RequestAutoMergeIntentStatus = "Active" | "Cancelled" | "Stopped" | "Fulfilled";

export type RequestAutoMergeStopReason = "RequestChanged" | "RequestClosed" | "AccessRevoked" | "ChecksFailed" | "ChecksConfigurationError" | "MergeConflict" | "RequestBranchMissing";

export type AuthorizeRequestAutoMergeRequest = { expected_revision_id: string, expected_head_oid: GitOid, };

export type CancelRequestAutoMergeRequest = { expected_intent_id: string, };

export type RequestAutoMergeIntentResponse = { id: string, revision_id: string, head_oid: GitOid, actor: RequestActorSummaryResponse, status: RequestAutoMergeIntentStatus, reason: RequestAutoMergeStopReason | null, created_at_unix: number, updated_at_unix: number, };

export type RequestAutoMergeResponse = { request_id: string, revision_id: string | null, head_oid: GitOid, intent: RequestAutoMergeIntentResponse | null, waiting_reason: string | null, can_enable: boolean, can_cancel: boolean, };

export type GitHubCheckStatus = "queued" | "in_progress" | "completed" | "waiting" | "requested" | "pending";

export type GitHubCheckConclusion = "success" | "neutral" | "skipped" | "failure" | "cancelled" | "timed_out" | "action_required" | "stale" | "startup_failure";

export type RequestGitHubPushState = "awaiting_approval" | "sending" | "sent" | "failed";

export type RequestGitHubPushResponse = { state: RequestGitHubPushState, branch: string, 
/**
 * Only maintainers see what GitHub answered.
 */
error: string | null, };

export type RequestCheckResponse = { "provider": "native", workflow_path: string, workflow_name: string, run_id: string | null, run_state: RunState | null, } | { "provider": "github", name: string, status: GitHubCheckStatus | null, conclusion: GitHubCheckConclusion | null, details_url: string | null, 
/**
 * The workflow run and job on Scope's run page that answer the
 * check, when it is a GitHub Actions job the viewer may open there.
 */
run: RequestCheckRunResponse | null, };

export type RequestCheckRunResponse = { run_id: string, job_id: string, };

export type RequestChecksResponse = { request_id: string, head_oid: GitOid, 
/**
 * `None` while the head has no evaluation: nothing is known about its checks yet.
 */
state: RequestCheckEvaluationState | null, message: string | null, checks: Array<RequestCheckResponse>, 
/**
 * Whether the viewer can start checks that wait for a maintainer.
 */
can_approve: boolean, 
/**
 * Set when the repository's checks run on GitHub and the head is on its
 * way there or waits for approval to go.
 */
github_push: RequestGitHubPushResponse | null, 
/**
 * Whether approving would run workflow files this request changes. Only
 * worked out for a viewer who can approve GitHub checks.
 */
changes_github_workflows: boolean, 
/**
 * Whether this private request's checks run in a public GitHub
 * repository, where everything Scope pushes is public.
 */
private_request_on_public_github: boolean, mergeability: RequestMergeabilityResponse, };

export type RequestEventResponse = { id: string, position: number, 
/**
 * Null once that account is deleted; clients show a deleted user.
 */
actor: RequestActorSummaryResponse | null, kind: RequestEventKind, payload: RequestEventPayload, created_at_unix: number, };

export type RequestEventPayload = { "Started": { identity: RequestIdentityAuditFact, } } | { "Submitted": { head_oid: string, } } | { "RevisionPushed": { old_head_oid: string, new_head_oid: string, note: string | null, } } | { "Merged": { head_oid: string, main_oid: string, } } | { "Closed": { head_oid: string, } } | { "IdentityEdited": { before: RequestIdentityAuditFact, after: RequestIdentityAuditFact, } } | { "DiscussionResolved": { discussion_id: string, } } | { "DiscussionReopened": { discussion_id: string, } } | { "AutoMergeEnabled": { intent_id: string, revision_id: string, head_oid: string, } } | { "AutoMergeCancelled": { intent_id: string, revision_id: string, head_oid: string, } } | { "AutoMergeStopped": { intent_id: string, revision_id: string, head_oid: string, reason: RequestAutoMergeStopReason, } } | { "AutoMergeFulfilled": { intent_id: string, revision_id: string, head_oid: string, main_oid: string, } };

export type RequestIdentityAuditFact = { title_sha256: string, title_byte_count: number, description_sha256: string, description_byte_count: number, };

export type RequestActorSummaryResponse = { id: string, handle: string, };

export type RequestDiscussionStatus = "Open" | "Resolved";

export type RequestDiscussionReplyReferenceResponse = { id: string, position: number, 
/**
 * Null once that account is deleted; clients show a deleted user.
 */
author: RequestActorSummaryResponse | null, body_markdown: string, };

export type RequestDiscussionReplyResponse = { id: string, discussion_id: string, position: number, 
/**
 * Null once that account is deleted; clients show a deleted user.
 */
author: RequestActorSummaryResponse | null, body_markdown: string, reply_to: RequestDiscussionReplyReferenceResponse | null, created_at_unix: number, };

export type RequestDiscussionSummaryResponse = { id: string, request_id: string, client_discussion_id: string, opened_position: number, last_activity_position: number, 
/**
 * Null once that account is deleted; clients show a deleted user.
 */
author: RequestActorSummaryResponse | null, body_markdown: string, anchor: RequestDiscussionAnchor | null, status: RequestDiscussionStatus, reply_count: number, read_through_position: number, unread_count: number, latest_replies: Array<RequestDiscussionReplyResponse>, created_at_unix: number, resolved_at_unix: number | null, resolved_by: RequestActorSummaryResponse | null, };

export type RequestDiscussionAnchor = { revision_id: string, revision_position: number, commit_oid: string | null, path: string | null, };

export type RequestDiscussionAnchorInput = { revision_id: string, commit_oid: string | null, path: string | null, };

export type RequestRevisionCommitResponse = { oid: string, parent_oids: Array<string>, author: string | null, authored_at_unix: number, message: string, change_count: number, files: Array<CommitFileResponse>, files_truncated: boolean, };

export type RequestRevisionInspectionState = "Complete" | "Incomplete" | "Unavailable";

export type RequestRevisionResponse = { id: string, position: number, 
/**
 * Null once that account is deleted; clients show a deleted user.
 */
actor: RequestActorSummaryResponse | null, old_head_oid: string | null, new_head_oid: string | null, commits: Array<RequestRevisionCommitResponse>, inspection: RequestRevisionInspectionState, created_at_unix: number, };

export type RequestRevisionListResponse = { review_revision_id: string | null, revisions: Array<RequestRevisionResponse>, has_earlier_revisions: boolean, };

export type RequestDiscussionPageResponse = { discussions: Array<RequestDiscussionSummaryResponse>, next_cursor: string | null, snapshot_version: number, };

export type RequestDiscussionRepliesPageResponse = { replies: Array<RequestDiscussionReplyResponse>, next_before_position: number | null, };

export type RequestDiscussionMutationResponse = { discussion: RequestDiscussionSummaryResponse, };

export type RequestDiscussionReplyMutationResponse = { discussion: RequestDiscussionSummaryResponse, reply: RequestDiscussionReplyResponse, };

export type RequestDiscussionChangesResponse = { discussions: Array<RequestDiscussionSummaryResponse>, through_position: number, has_more: boolean, };

export type RequestDiscussionReadResponse = { read_through_position: number, };

export type RequestActivityPageResponse = { events: Array<RequestEventResponse>, through_position: number, };

export type RequestCloseResponse = { deleted: boolean, request: RequestSummaryResponse | null, };

export type StartRequestRequest = { name: string, title: string | null, view: ViewId, };

export type SubmitRequestRequest = Record<symbol, never>;

export type MergeRequestRequest = { expected_head_oid: GitOid, };

export type ApproveRequestChecksRequest = { expected_head_oid: GitOid, };

export type EditRequestIdentityRequest = { title: string | null, description_markdown: string | null, expected_description_markdown: string | null, };

export type CreateRequestDiscussionRequest = { body_markdown: string, client_discussion_id: string, anchor: RequestDiscussionAnchorInput | null, };

export type CreateRequestDiscussionReplyRequest = { body_markdown: string, client_reply_id: string, reply_to_reply_id: string | null, wait_after_reply: boolean, };

export type MarkRequestDiscussionReadRequest = { through_position: number, };

export type RepoChangeKind = "Connected" | "Lagged" | "DependenciesChanged" | "GitHubWorkflowRunsChanged" | { "GitHubWorkflowRunChanged": { github_run_id: number, } } | { "RepositoryChanged": { reason: string, } } | { "RequestTimelineChanged": { request_id: string, discussion_id: string, through_position: number, view: ViewId, } } | { "RequestAttachmentChanged": { request_id: string, attachment_id: string, view: ViewId, } } | { "RunChanged": { run_id: string, change: RunChangeKind, } };

export type RunChangeKind = "Created" | "StatusChanged" | "LogsAppended";

export type RunState = "queued" | "dispatching" | "running" | "succeeded" | "failed" | "canceled" | "lost";

export type RunResponse = { id: string, repository_id: string, workflow_name: string, git_oid: string, state: RunState, cancellation_requested: boolean, logs_truncated: boolean, created_at_unix: number, updated_at_unix: number, completed_at_unix: number | null, };

export type RepositoryRunTrigger = "manual" | "push-main" | "request";

export type RepositoryRunSummaryResponse = { id: string, workflow_name: string, git_oid: string, trigger: RepositoryRunTrigger, state: RunState, cancellation_requested: boolean, created_at_unix: number, updated_at_unix: number, completed_at_unix: number | null, can_cancel: boolean, can_retry: boolean, };

export type RepositoryRunJobState = "blocked" | "queued" | "dispatching" | "running" | "succeeded" | "failed" | "skipped" | "canceled" | "lost";

export type RepositoryRunJobResponse = { key: string, needs: Array<string>, pinned_container_image: string, state: RepositoryRunJobState, created_at_unix: number, started_at_unix: number | null, updated_at_unix: number, completed_at_unix: number | null, };

export type RepositoryRunJobDetailResponse = { job: RepositoryRunJobResponse, attempts: Array<RepositoryRunAttemptResponse>, };

export type AttemptState = "dispatching" | "running" | "succeeded" | "failed" | "canceled" | "lost";

export type StepState = "pending" | "running" | "succeeded" | "failed" | "canceled" | "lost" | "skipped";

export type RepositoryRunTerminalReason = { "kind": "step-failed", step_index: number, exit_code: number, } | { "kind": "timed-out", step_index: number | null, } | { "kind": "canceled", step_index: number | null, } | { "kind": "execution-lost", step_index: number | null, } | { "kind": "dispatch-attempts-exhausted" } | { "kind": "runtime-setup-failed", exit_code: number, message: string, };

export type CacheColdReason = "metadata-missing" | "metadata-invalid" | "metadata-not-ready";

export type CachePreparation = { "kind": "exact" } | { "kind": "compatible" } | { "kind": "cold", reason: CacheColdReason, };

export type CacheFinalState = "pending" | "ready" | "evicted";

export type RepositoryRunCacheObservationResponse = { workflow_path: string, job_key: string, identity_digest: string, preparation: CachePreparation, key_ms: number, metadata_ms: number, size_bytes: number, download_verify_ms: number, sync_ms: number, extraction_ms: number, prepare_ms: number, final_state: CacheFinalState, finalize_ms: number | null, };

export type RepositoryRunCacheSetupObservationResponse = { authorization_ms: number, wall_ms: number, };

export type RepositoryRunCacheResponse = { name: string, path: string, observation: RepositoryRunCacheObservationResponse | null, };

export type RepositoryRunStepResponse = { index: number, name: string, command: string, state: StepState, started_at_unix: number | null, completed_at_unix: number | null, exit_code: number | null, };

export type RepositoryRunAttemptResponse = { id: string, number: number, external_run_id: string | null, runtime_version: string, state: AttemptState, created_at_unix: number, started_at_unix: number | null, completed_at_unix: number | null, terminal_reason: RepositoryRunTerminalReason | null, cache_setup: RepositoryRunCacheSetupObservationResponse | null, caches: Array<RepositoryRunCacheResponse>, steps: Array<RepositoryRunStepResponse>, };

export type RepositoryRunWorkflowResponse = { key: string, name: string, path: string, manual: boolean, push_main: boolean, job_count: number, };

export type RepositoryRunWorkflowListResponse = { workflows: Array<RepositoryRunWorkflowResponse>, 
/**
 * Whether the repository's owner is listed for Scope's hosted runner.
 */
native_runs_available: boolean, };

export type RepositoryRunHistoryPageResponse = { runs: Array<RepositoryRunSummaryResponse>, next_cursor: string | null, };

export type RepositoryRunLogResponse = { byte_length: number, position: number, sequence: number, text: string, created_at_unix: number, };

export type RepositoryRunDetailResponse = { run: RepositoryRunSummaryResponse, jobs: Array<RepositoryRunJobDetailResponse>, };

export type RepositoryRunStepLogPageResponse = { logs: Array<RepositoryRunLogResponse>, next_after: number, logs_truncated: boolean, has_earlier: boolean, has_more: boolean, };

export const ApiRouteTemplates = {
  account: "/v1/account",
  accountSession: "/v1/session",
  cliDeviceLoginComplete: "/v1/cli/device-login/{user_code}/complete",
  cliBrowserLoginComplete: "/v1/cli/browser-login/{request_id}/complete",
  cliExchangeGrants: "/v1/cli/exchange-grants",
  cliSessions: "/v1/cli/sessions",
  cliSessionById: "/v1/cli/sessions/{session_id}",
  repos: "/v1/repos",
  ownerRepositories: "/v1/users/{handle}/repos",
  repo: "/v1/repos/{owner}/{repo}",
  repoConfig: "/v1/repos/{owner}/{repo}/config",
  repoMetadata: "/v1/repos/{owner}/{repo}/metadata",
  repoGitHub: "/v1/repos/{owner}/{repo}/github",
  repoGitHubAuthorize: "/v1/repos/{owner}/{repo}/github/authorize",
  repoGitHubRequiredChecks: "/v1/repos/{owner}/{repo}/github/required-checks",
  repoGitHubPublicConfirmation: "/v1/repos/{owner}/{repo}/github/public-confirmation",
  repoGitHubSetupCheck: "/v1/repos/{owner}/{repo}/github/setup-check",
  repoGitHubWorkflowRuns: "/v1/repos/{owner}/{repo}/github/workflow-runs",
  repoGitHubWorkflowRun: "/v1/repos/{owner}/{repo}/github/workflow-runs/{run_id}",
  repoGitHubWorkflowJobLog: "/v1/repos/{owner}/{repo}/github/workflow-runs/{run_id}/jobs/{job_id}/log",
  repoGitHubRunImport: "/v1/repos/{owner}/{repo}/github/run-import",
  githubSetup: "/v1/github/setup",
  repoDependencies: "/v1/repos/{owner}/{repo}/dependencies",
  repoRunWorkflows: "/v1/repos/{owner}/{repo}/run-workflows",
  repoRuns: "/v1/repos/{owner}/{repo}/runs",
  repoRunDetail: "/v1/repos/{owner}/{repo}/runs/{run_id}/detail",
  repoRunStepLogs: "/v1/repos/{owner}/{repo}/runs/{run_id}/attempts/{attempt_id}/steps/{step_index}/logs",
  repoRunCancel: "/v1/repos/{owner}/{repo}/runs/{run_id}/cancel",
  repoRunRetry: "/v1/repos/{owner}/{repo}/runs/{run_id}/retry",
  repoPushIntents: "/v1/repos/{owner}/{repo}/push-intents",
  repoRequests: "/v1/repos/{owner}/{repo}/requests",
  repoRequestQueue: "/v1/repos/{owner}/{repo}/requests/queue",
  repoRequestAttention: "/v1/repos/{owner}/{repo}/requests/{request_id}/attention",
  repoRequest: "/v1/repos/{owner}/{repo}/requests/{request_id}",
  repoRequestSubmit: "/v1/repos/{owner}/{repo}/requests/{request_id}/submit",
  repoRequestMerge: "/v1/repos/{owner}/{repo}/requests/{request_id}/merge",
  repoRequestAutoMerge: "/v1/repos/{owner}/{repo}/requests/{request_id}/auto-merge",
  repoRequestChecks: "/v1/repos/{owner}/{repo}/requests/{request_id}/checks",
  repoRequestChecksApprove: "/v1/repos/{owner}/{repo}/requests/{request_id}/checks/approve",
  repoRequestRatings: "/v1/repos/{owner}/{repo}/requests/{request_id}/ratings",
  repoRequestInvitees: "/v1/repos/{owner}/{repo}/requests/{request_id}/invitees",
  repoRequestInviteesMe: "/v1/repos/{owner}/{repo}/requests/{request_id}/invitees/me",
  repoRequestAttachments: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments",
  repoRequestAttachmentLimits: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments/limits",
  repoRequestAttachmentPrepare: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments/prepare",
  repoRequestAttachment: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments/{attachment_id}",
  repoRequestAttachmentFinish: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments/{attachment_id}/finish",
  repoRequestAttachmentRetry: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments/{attachment_id}/retry",
  repoRequestAttachmentMediaGrant: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments/{attachment_id}/media-grant",
  repoFiles: "/v1/repos/{owner}/{repo}/files",
  repoFileContent: "/v1/repos/{owner}/{repo}/files/content",
  repoRequestRevisions: "/v1/repos/{owner}/{repo}/requests/{request_id}/changes",
  repoRequestRevisionCommitFileDiff: "/v1/repos/{owner}/{repo}/requests/{request_id}/changes/{revision_id}/commits/{commit_oid}/file-diff",
  repoRequestDiscussions: "/v1/repos/{owner}/{repo}/requests/{request_id}/timeline",
  repoRequestDiscussionChanges: "/v1/repos/{owner}/{repo}/requests/{request_id}/timeline/changes",
  repoRequestDiscussionReplies: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/replies",
  repoRequestDiscussionResolve: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/resolve",
  repoRequestDiscussionReopen: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/reopen",
  repoRequestDiscussionReopenAndReply: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/reopen-and-reply",
  repoRequestDiscussionRead: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/read",
  repoRequestActivity: "/v1/repos/{owner}/{repo}/requests/{request_id}/activity",
  repoEvents: "/v1/repos/{owner}/{repo}/events",
  repoHistory: "/v1/repos/{owner}/{repo}/history",
  repoHistoryEntry: "/v1/repos/{owner}/{repo}/history/{entry_id}",
  repoHistoryEntryFileDiff: "/v1/repos/{owner}/{repo}/history/{entry_id}/file-diff",
  repoMembers: "/v1/repos/{owner}/{repo}/members",
  repoInvites: "/v1/repos/{owner}/{repo}/invites",
  repoInvite: "/v1/repos/{owner}/{repo}/invites/{invite_id}",
  repoInviteLinks: "/v1/repos/{owner}/{repo}/invites/{invite_id}/links",
  repoInviteEmails: "/v1/repos/{owner}/{repo}/invites/{invite_id}/emails",
  repoMember: "/v1/repos/{owner}/{repo}/members/{member_user_id}",
  repositoryInvite: "/v1/repository-invites/{token}",
  repositoryInviteAccept: "/v1/repository-invites/{token}/accept",
  repoProjectionPreview: "/v1/repos/{owner}/{repo}/projection-preview",
  gitRepo: "/git/{view}/{org}/{repo}",
} as const;

export function buildApiPath(
  template: string,
  params: Readonly<Record<string, string>> = {},
): string {
  return template.replace(/\{([^}]+)\}/g, (_match, key: string) => {
    const value = params[key]
    if (value === undefined) throw new Error(`Missing API route parameter: ${key}`)
    return encodeURIComponent(value)
  })
}
