// This file is generated from Rust API response/request types.
// Run `pnpm generate:api-contract` from web/ to update it.
// Do not edit this file by hand.

export type ErrorCode = "attachment_upload_expired" | "bad_request" | "cli_upgrade_required" | "conflict" | "forbidden" | "internal" | "not_found" | "not_implemented" | "payload_too_large" | "protected_path" | "service_unavailable" | "too_many_requests" | "unauthorized";

export type ErrorFields = { paths?: Array<string>, installed_protocol?: number | null, supported_protocol?: number | null, };

export type ErrorResponse = { code: ErrorCode, message: string, error_reference?: string | null, instruction?: string | null, fields?: ErrorFields, retryable: boolean, };

export type Visibility = "Public" | "Private";

export type RepositoryActor = "Public" | "Member" | "Owner";

export type RepositoryMemberPermissions = { can_push: boolean, can_change_file_visibility: boolean, can_apply_changes: boolean, };

export type RepositoryInviteState = "Pending" | "Accepted" | "Revoked" | "Expired";

export type RepoLifecycleState = "AwaitingFirstPush" | "Ready";

export type RepoChangeEvent = { repo_id: string, incarnation_id: string, version: number, kind: RepoChangeKind, };

export type FirstPushTokenStatus = "Active" | "Expired" | "Used";

export type FileChangeKind = "Added" | "Modified" | "Deleted";

export type ConfigVisibility = "public" | "private";

export type RepoConfig = { $schema?: string | null, kind: string, version: number, visibility: RepoConfigVisibility, history: RepoConfigHistory, };

export type RepoConfigVisibility = { default: ConfigVisibility, rules: Array<RepoConfigVisibilityRule>, };

export type RepoConfigVisibilityRule = { path: string, visibility: ConfigVisibility, };

export type RepoConfigHistory = { rewrites: Array<HistoryRewriteRequest>, };

export type HistoryRewriteRequest = { path: string, action: HistoryRewriteAction, };

export type HistoryRewriteAction = "redact-public-history";

export type RequestActorRole = "Public" | "Member" | "Owner";

export type RequestAudience = "Public" | "Private";

export type RequestState = "Draft" | "Open" | "Closed" | "Merged";

export type RequestAttachmentTargetKind = "Description" | "Discussion" | "Reply";

export type RequestAttachmentTargetInput = { kind: RequestAttachmentTargetKind, discussion_id: string | null, };

export type RequestAttachmentKind = "Photo" | "Video";

export type RequestAttachmentState = "Prepared" | "Uploaded" | "Processing" | "Ready" | "Failed" | "Rejected";

export type RequestAttachmentDerivativeKind = "ImagePreview" | "VideoPlayback" | "VideoPoster";

export type RequestAttachmentFailureCode = "InvalidMedia" | "CorruptMedia" | "UnsupportedMedia" | "MediaLimitExceeded" | "CodecFailed" | "StorageUnavailable" | "Internal";

export type RequestAttachmentLimitsResponse = { accepted_photo_media_types: Array<string>, accepted_video_media_types: Array<string>, max_photo_bytes: number, max_video_bytes: number, max_video_duration_seconds: number, max_attachments_per_content: number, max_request_source_bytes: number, max_repository_storage_bytes: number, max_photo_pixels: number, preferred_part_bytes: number, max_concurrent_parts: number, incomplete_upload_ttl_seconds: number, unbound_attachment_ttl_seconds: number, };

export type PrepareRequestAttachmentRequest = { operation_id: string, target: RequestAttachmentTargetInput, filename: string, declared_media_type: string, size_bytes: number, sha256: string, };

export type PrepareRequestAttachmentResponse = { attachment: RequestAttachmentResponse, transfer: RequestAttachmentTransferResponse, };

export type RequestAttachmentTransferResponse = { upload_id: string, media_base_url: string, grant: string, expires_at_unix: number, preferred_part_bytes: number, max_concurrent_parts: number, acknowledged_parts: Array<RequestAttachmentPartReceiptResponse>, };

export type RequestAttachmentPartReceiptResponse = { part_number: number, size_bytes: number, sha256: string, };

export type FinishRequestAttachmentRequest = { upload_id: string, parts: Array<RequestAttachmentPartReceiptResponse>, };

export type RetryRequestAttachmentRequest = { operation_id: string, };

export type RequestAttachmentListResponse = { attachments: Array<RequestAttachmentResponse>, };

export type RequestAttachmentResponse = { id: string, request_id: string, uploader_user_id: string, filename: string, declared_media_type: string, detected_media_type: string | null, kind: RequestAttachmentKind, size_bytes: number, sha256: string, state: RequestAttachmentState, original_download_available: boolean, failure: RequestAttachmentFailureResponse | null, image: RequestAttachmentImageMetadataResponse | null, video: RequestAttachmentVideoMetadataResponse | null, derivatives: Array<RequestAttachmentDerivativeResponse>, created_at_unix: number, updated_at_unix: number, };

export type RequestAttachmentImageMetadataResponse = { width: number, height: number, };

export type RequestAttachmentVideoMetadataResponse = { width: number, height: number, duration_millis: number, };

export type RequestAttachmentDerivativeResponse = { id: string, kind: RequestAttachmentDerivativeKind, media_type: string, size_bytes: number, width: number | null, height: number | null, duration_millis: number | null, };

export type RequestAttachmentFailureResponse = { code: RequestAttachmentFailureCode, message: string, retryable: boolean, };

export type RequestAttachmentMediaTarget = { "kind": "original" } | { "kind": "derivative", derivative_id: string, };

export type CreateRequestAttachmentMediaGrantRequest = { target: RequestAttachmentMediaTarget, };

export type CreateRequestAttachmentMediaGrantResponse = { media_url: string, grant: string, expires_at_unix: number, };

export type RequestAttachmentMediaGrantMethod = "Get";

export type RequestAttachmentMediaGrantClaims = { attachment_id: string, repository_id: string, request_id: string, viewer_user_id: string | null, method: RequestAttachmentMediaGrantMethod, target: RequestAttachmentMediaTarget, expires_at_unix: number, };

export type RequestAttachmentUploadGrantClaims = { attachment_id: string, repository_id: string, request_id: string, uploader_user_id: string, upload_id: string, expires_at_unix: number, };

export type GitOid = string;

export type RequestEventKind = "Started" | "Submitted" | "RevisionPushed" | "Merged" | "Closed" | "IdentityEdited" | "DiscussionResolved" | "DiscussionReopened";

export type ProjectionPreviewAudience = "private" | "public";

export type ProjectionPreviewSource = "live";

export type AccountSessionResponse = { identity: SessionIdentity | null, user: UserResponse | null, };

export type UserResponse = { id: string, handle: string, email: string, email_verified: boolean, };

export type SessionResponse = { identity: SessionIdentity | null, repo: SessionRepo, principal_id: string, capabilities: SessionCapabilities, };

export type SessionIdentity = { user_id: string, email: string | null, email_verified: boolean, };

export type SessionRepo = { id: string, lifecycle_state: RepoLifecycleState, access: RepositoryAccessResponse, };

export type SessionCapabilities = { read: boolean, can_read_private_files: boolean, can_push: boolean, can_change_file_visibility: boolean, can_apply_changes: boolean, can_manage_members: boolean, can_delete_repo: boolean, };

export type DeviceLoginStatus = "Pending" | "Complete";

export type DeviceLoginStartResponse = { device_code: string, user_code: string, verification_url: string, expires_at_unix: number, poll_interval_secs: number, };

export type DeviceLoginPollResponse = { status: DeviceLoginStatus, session_token: string | null, expires_at_unix: number, identity: SessionIdentity | null, };

export type DeviceLoginCompleteResponse = { status: DeviceLoginStatus, };

export type BrowserLoginStartRequest = { callback_url: string, };

export type BrowserLoginStartResponse = { request_id: string, request_secret: string, authorization_url: string, expires_at_unix: number, };

export type BrowserLoginCompleteResponse = { callback_url: string, };

export type BrowserLoginExchangeRequest = { request_secret: string, callback_code: string, };

export type CliSessionTokenResponse = { session_token: string, expires_at_unix: number, identity: SessionIdentity, };

export type CliExchangeGrantResponse = { exchange_token: string, expires_at_unix: number, };

export type CliExchangeGrantExchangeRequest = { exchange_token: string, };

export type CliSessionsResponse = { sessions: Array<CliSessionResponse>, };

export type CliSessionResponse = { id: string, label: string, created_at_unix: number, last_used_at_unix: number | null, expires_at_unix: number, };

export type RepoSummaryResponse = { description: string | null, website_url: string | null, id: string, owner_handle: string, name: string, git_remote_url: string, lifecycle_state: RepoLifecycleState, change_version: number, access: RepositoryAccessResponse, open_request_count: number, request_permissions: RepoRequestPermissionsResponse, };

export type OwnerProfileResponse = { handle: string, repositories: Array<RepoSummaryResponse>, };

export type RepoRequestPermissionsResponse = { can_start_request: boolean, };

export type CreateRepoRequest = { name: string, file_default_visibility: Visibility | null, };

export type UpdateRepoMetadataRequest = { description: string | null, website_url: string | null, };

export type CreateRepoResponse = { repo: RepoSummaryResponse, init: RepoInitResponse, };

export type DeleteRepoResponse = { id: string, deleted: boolean, };

export type CreatePushIntentRequest = { head_oid: string, base_config_hash: string, config: RepoConfig, };

export type CreatePushIntentResponse = { token: string, base_head_oid: GitOid | null, expires_at_unix: number, };

export type RepoInitResponse = { repo: RepoSummaryResponse, git_remote_url: string, remote_name: string, push_branch: string, token: FirstPushTokenResponse | null, push_token: GitPushTokenResponse | null, };

export type RepoConfigResponse = { config: RepoConfig, config_hash: string, lifecycle_state: RepoLifecycleState, access: RepositoryAccessResponse, head_oid: string | null, };

export type FirstPushTokenResponse = { status: FirstPushTokenStatus, created_at_unix: number, expires_at_unix: number, used_at_unix: number | null, secret: string | null, };

export type GitPushTokenResponse = { created_at_unix: number, secret: string | null, };

export type RepoFileResponse = { path: string, oid: string, tracked: boolean, visibility: Visibility, };

export type RepoFileContentRequest = { path: string, };

export type RepoFileContentResponse = { path: string, oid: string, visibility: Visibility, size_bytes: number, content: ReviewFileContentResponse, };

export type RepositoryAccessResponse = { actor: RepositoryActor, can_read_private_files: boolean, can_push: boolean, can_change_file_visibility: boolean, can_apply_changes: boolean, can_manage_members: boolean, can_delete_repo: boolean, };

export type RepositoryCollaborationResponse = { members: Array<RepositoryMemberResponse>, invites: Array<RepositoryInviteResponse>, };

export type RepositoryMemberResponse = { user_id: string, handle: string, email: string, permissions: RepositoryMemberPermissions, created_at_unix: number, updated_at_unix: number, };

export type RepositoryInviteResponse = { id: string, invited_email: string, permissions: RepositoryMemberPermissions, state: RepositoryInviteState, expires_at_unix: number, };

export type CreateRepositoryInviteRequest = { email: string, permissions: RepositoryMemberPermissions, };

export type CreateRepositoryInviteResponse = { invite: RepositoryInviteResponse, invite_url: string, };

export type UpdateRepositoryMemberRequest = { permissions: RepositoryMemberPermissions, };

export type RepositoryInviteLookupResponse = { repo_id: string, owner_handle: string, repo_name: string, invited_email: string, permissions: RepositoryMemberPermissions, expires_at_unix: number, };

export type AcceptRepositoryInviteResponse = { repo: RepoSummaryResponse, member: RepositoryMemberResponse, };

export type HistoryPageRequest = { feed: HistoryFeed | null, audience: ProjectionPreviewAudience | null, before: string | null, };

export type HistoryEntryRequest = { audience: ProjectionPreviewAudience | null, };

export type HistoryEntryFileDiffRequest = { visibility_change: string | null, audience: ProjectionPreviewAudience | null, path: string, };

export type RequestFileDiffRequest = { path: string, };

export type ReviewFileContentResponse = { "kind": "text", text: string, } | { "kind": "binary", oid: string, size_bytes: number, };

export type ReviewFileDiffResponse = { path: string, kind: FileChangeKind, old_mode: string | null, new_mode: string | null, old_content: ReviewFileContentResponse | null, new_content: ReviewFileContentResponse | null, };

export type HistoryPageResponse = { feed: HistoryFeed, audience: ProjectionPreviewAudience, repo_id: string, view_key: string, generation: string, head_oid: string | null, entries: Array<HistoryEntrySummaryResponse>, next_cursor: string | null, };

export type HistoryEntrySummaryResponse = { occurred_at_unix: number | null, id: string, source_id: string, parent_id: string | null, kind: HistoryEntryKind, author: string | null, message: string, file_change_count: number, visibility_summary: HistoryVisibilitySummaryResponse, };

export type HistoryEntryKind = "push" | "merged_request" | "visibility_change";

export type HistoryFeed = "updates" | "all";

export type HistoryEntryDetailResponse = { audience: ProjectionPreviewAudience, repo_id: string, view_key: string, id: string, source_id: string, parent_id: string | null, kind: HistoryEntryKind, author: string | null, message: string, file_change_count: number, visibility_summary: HistoryVisibilitySummaryResponse, files: Array<HistoryEntryFileResponse>, visibility_changes: Array<HistoryVisibilityChangeResponse>, };

export type HistoryEntryFileResponse = { path: string, kind: FileChangeKind, old_mode: string | null, new_mode: string | null, old_oid: string | null, new_oid: string | null, visibility: Visibility, };

export type HistoryVisibilitySummaryResponse = { made_public_count: number, made_private_count: number, };

export type HistoryVisibilityChangeResponse = { id: string, file: HistoryEntryFileResponse | null, path: string, old_visibility: Visibility, new_visibility: Visibility, };

export type CommitFileResponse = { path: string, kind: FileChangeKind, old_mode: string | null, new_mode: string | null, old_oid: string | null, new_oid: string | null, visibility: Visibility, };

export type ProjectionPreviewRequest = { audience: ProjectionPreviewAudience, source: ProjectionPreviewSource | null, };

export type ProjectionPreviewResponse = { audience: ProjectionPreviewAudience, source: ProjectionPreviewSource, repo_id: string, view_key: string, head_oid: string | null, files: Array<ProjectionPreviewFileResponse>, commits: Array<ProjectionPreviewCommitResponse>, summary: ProjectionPreviewSummaryResponse, };

export type ProjectionPreviewFileResponse = { path: string, oid: string, visibility: Visibility, };

export type ProjectionPreviewCommitResponse = { projected_id: string, logical_commit_id: string, parent_projected_id: string | null, author: string | null, message: string, visibility: ProjectionPreviewCommitVisibilityResponse, change_count: number, };

export type ProjectionPreviewCommitVisibilityResponse = "FullyPublic" | "Mixed" | "FullyPrivate";

export type ProjectionPreviewSummaryResponse = { visible_files: number, hidden_files: number, visible_commits: number, hidden_commits: number, };

export type RequestQueueSection = "active" | "unclaimed" | "set_aside" | "done";

export type RequestAttentionState = "active" | "waiting" | "snoozed" | "settled";

export type RequestAttentionReason = "authored" | "invited" | "claimed" | "unclaimed" | "claimed_elsewhere" | "new_activity" | "restored" | "snooze_expired" | "waiting" | "snoozed" | "settled" | "open" | "closed" | "merged";

export type RequestAttentionResponse = { state: RequestAttentionState, reason: RequestAttentionReason, activity_version: number, through_activity_version: number, snoozed_until_unix: number | null, can_claim: boolean, can_set_aside: boolean, can_restore: boolean, can_release: boolean, };

export type RequestAttentionActionRequest = { "action": "claim", expected_activity_version: number, } | { "action": "wait", expected_activity_version: number, } | { "action": "settle", expected_activity_version: number, } | { "action": "snooze", expected_activity_version: number, until_unix: number, } | { "action": "restore", expected_activity_version: number, } | { "action": "release", expected_activity_version: number, };

export type RequestAttentionMutationResponse = { attention: RequestAttentionResponse, claimer: RequestActorSummaryResponse | null, };

export type RequestQueueItemResponse = { attention_at_unix: number, request: RequestListItemResponse, author: RequestActorSummaryResponse, attention: RequestAttentionResponse, claimer: RequestActorSummaryResponse | null, };

export type RequestQueuePageResponse = { requests: Array<RequestQueueItemResponse>, next_cursor: string | null, next_attention_at_unix: number | null, };

export type RequestListResponse = { requests: Array<RequestListItemResponse>, next_cursor: string | null, };

export type RequestDetailResponse = { request: RequestSummaryResponse, };

export type CreateRequestRatingRequest = { score: number, reason: string, };

export type RequestRatingParticipantResponse = { id: string, handle: string, rating_score_sum: number, rating_count: number, };

export type RequestRatingResponse = { id: string, request_id: string, rater: RequestRatingParticipantResponse, subject: RequestRatingParticipantResponse, score: number, reason: string, created_at_unix: number, };

export type RequestRatingsResponse = { ratings: Array<RequestRatingResponse>, eligible_subject: RequestRatingParticipantResponse | null, };

export type RequestMutationResponse = { request: RequestSummaryResponse, };

export type RequestListItemResponse = { id: string, name: string, title: string, author_role: RequestActorRole, audience: RequestAudience, head_oid: GitOid, state: RequestState, submitted_at_unix: number | null, updated_at_unix: number, mergeability: RequestMergeabilityResponse, };

export type RequestSummaryResponse = { id: string, name: string, title: string, description_markdown: string, author_user_id: string, author_role: RequestActorRole, audience: RequestAudience, base_main_oid: GitOid, head_oid: GitOid, state: RequestState, activity_version: number, submitted_at_unix: number | null, closed_at_unix: number | null, closed_by_user_id: string | null, merged_at_unix: number | null, merged_by_user_id: string | null, merged_head_oid: GitOid | null, merged_main_oid: GitOid | null, created_at_unix: number, updated_at_unix: number, invitees: Array<RequestInviteeResponse>, permissions: RequestPermissionsResponse, mergeability: RequestMergeabilityResponse, };

export type RequestInviteeResponse = { user: RequestActorSummaryResponse, invited_by_user_id: string, created_at_unix: number, };

export type AddRequestInviteeRequest = { handle: string, };

export type RemoveRequestInviteeRequest = { handle: string, };

export type RequestInviteeMutationResponse = { request: RequestSummaryResponse, invitee: RequestInviteeResponse, };

export type LeaveRequestResponse = { invitee: RequestInviteeResponse, };

export type RequestPermissionsResponse = { can_view_activity: boolean, can_open_discussion: boolean, can_reply_to_discussion: boolean, can_wait_after_reply: boolean, can_edit_identity: boolean, can_pull_branch: boolean, can_push_branch: boolean, can_submit: boolean, can_manage_invitees: boolean, can_leave_request: boolean, can_close: boolean, can_merge: boolean, };

export type RequestMergeabilityStatus = "Ready" | "Draft" | "Closed" | "Merged" | "NotMaintainer" | "MissingRequestBranch";

export type RequestMergeabilityResponse = { status: RequestMergeabilityStatus, current_main_oid: GitOid | null, request_head_oid: GitOid, reason: string | null, };

export type RequestEventResponse = { id: string, position: number, actor: RequestActorSummaryResponse, kind: RequestEventKind, payload: RequestEventPayload, created_at_unix: number, };

export type RequestEventPayload = { "Started": { identity: RequestIdentityAuditFact, } } | { "Submitted": { head_oid: string, } } | { "RevisionPushed": { old_head_oid: string, new_head_oid: string, note: string | null, } } | { "Merged": { head_oid: string, main_oid: string, } } | { "Closed": { head_oid: string, } } | { "IdentityEdited": { before: RequestIdentityAuditFact, after: RequestIdentityAuditFact, } } | { "DiscussionResolved": { discussion_id: string, } } | { "DiscussionReopened": { discussion_id: string, } };

export type RequestIdentityAuditFact = { title_sha256: string, title_byte_count: number, description_sha256: string, description_byte_count: number, };

export type RequestActorSummaryResponse = { id: string, handle: string, };

export type RequestDiscussionStatus = "Open" | "Resolved";

export type RequestDiscussionReplyReferenceResponse = { id: string, position: number, author: RequestActorSummaryResponse, body_markdown: string, };

export type RequestDiscussionReplyResponse = { id: string, discussion_id: string, position: number, author: RequestActorSummaryResponse, body_markdown: string, reply_to: RequestDiscussionReplyReferenceResponse | null, created_at_unix: number, };

export type RequestDiscussionSummaryResponse = { id: string, request_id: string, client_discussion_id: string, opened_position: number, last_activity_position: number, author: RequestActorSummaryResponse, body_markdown: string, anchor: RequestDiscussionAnchor | null, status: RequestDiscussionStatus, reply_count: number, read_through_position: number, unread_count: number, latest_replies: Array<RequestDiscussionReplyResponse>, created_at_unix: number, resolved_at_unix: number | null, resolved_by: RequestActorSummaryResponse | null, };

export type RequestDiscussionAnchor = { revision_id: string, revision_position: number, commit_oid: string | null, path: string | null, };

export type RequestDiscussionAnchorInput = { revision_id: string, commit_oid: string | null, path: string | null, };

export type RequestRevisionCommitResponse = { oid: string, parent_oids: Array<string>, author: string | null, authored_at_unix: number, message: string, change_count: number, files: Array<CommitFileResponse>, files_truncated: boolean, };

export type RequestRevisionInspectionState = "Complete" | "Incomplete" | "Unavailable";

export type RequestRevisionResponse = { id: string, position: number, actor: RequestActorSummaryResponse, old_head_oid: string | null, new_head_oid: string | null, commits: Array<RequestRevisionCommitResponse>, inspection: RequestRevisionInspectionState, created_at_unix: number, };

export type RequestRevisionListResponse = { review_revision_id: string | null, revisions: Array<RequestRevisionResponse>, has_earlier_revisions: boolean, };

export type RequestDiscussionPageResponse = { discussions: Array<RequestDiscussionSummaryResponse>, next_cursor: string | null, snapshot_version: number, };

export type RequestDiscussionRepliesPageResponse = { replies: Array<RequestDiscussionReplyResponse>, next_before_position: number | null, };

export type RequestDiscussionMutationResponse = { discussion: RequestDiscussionSummaryResponse, };

export type RequestDiscussionReplyMutationResponse = { discussion: RequestDiscussionSummaryResponse, reply: RequestDiscussionReplyResponse, };

export type RequestDiscussionChangesResponse = { discussions: Array<RequestDiscussionSummaryResponse>, through_position: number, has_more: boolean, };

export type RequestDiscussionReadResponse = { read_through_position: number, };

export type RequestActivityPageResponse = { events: Array<RequestEventResponse>, through_position: number, };

export type RequestCloseResponse = { deleted: boolean, request: RequestSummaryResponse | null, };

export type StartRequestRequest = { name: string, title: string | null, audience: RequestAudience, };

export type SubmitRequestRequest = Record<symbol, never>;

export type EditRequestIdentityRequest = { title: string | null, description_markdown: string | null, expected_description_markdown: string | null, };

export type CreateRequestDiscussionRequest = { body_markdown: string, client_discussion_id: string, anchor: RequestDiscussionAnchorInput | null, };

export type CreateRequestDiscussionReplyRequest = { body_markdown: string, client_reply_id: string, reply_to_reply_id: string | null, wait_after_reply: boolean, };

export type ReopenAndReplyRequest = { body_markdown: string, client_reply_id: string, reply_to_reply_id: string | null, wait_after_reply: boolean, };

export type MarkRequestDiscussionReadRequest = { through_position: number, };

export type RepoChangeKind = "Connected" | "Lagged" | { "RepositoryChanged": { reason: string, } } | { "RequestTimelineChanged": { request_id: string, discussion_id: string, through_position: number, audience: RequestAudience, } } | { "RequestAttachmentChanged": { request_id: string, attachment_id: string, audience: RequestAudience, } } | { "RunChanged": { run_id: string, change: RunChangeKind, } };

export type RunChangeKind = "Created" | "StatusChanged" | "LogsAppended";

export type RunState = "queued" | "dispatching" | "running" | "succeeded" | "failed" | "canceled" | "lost";

export type RunResponse = { id: string, repository_id: string, workflow_name: string, git_oid: string, state: RunState, cancellation_requested: boolean, logs_truncated: boolean, created_at_unix: number, updated_at_unix: number, completed_at_unix: number | null, };

export type RepositoryRunState = "queued" | "dispatching" | "running" | "succeeded" | "failed" | "canceled" | "lost";

export type RepositoryRunTrigger = "manual" | "push-main";

export type RepositoryRunSummaryResponse = { id: string, workflow_name: string, git_oid: string, trigger: RepositoryRunTrigger, state: RepositoryRunState, cancellation_requested: boolean, created_at_unix: number, updated_at_unix: number, completed_at_unix: number | null, can_cancel: boolean, can_retry: boolean, };

export type RepositoryRunJobState = "blocked" | "queued" | "dispatching" | "running" | "succeeded" | "failed" | "skipped" | "canceled" | "lost";

export type RepositoryRunJobResponse = { key: string, needs: Array<string>, pinned_container_image: string, state: RepositoryRunJobState, created_at_unix: number, started_at_unix: number | null, updated_at_unix: number, completed_at_unix: number | null, };

export type RepositoryRunJobDetailResponse = { job: RepositoryRunJobResponse, attempts: Array<RepositoryRunAttemptResponse>, };

export type RepositoryRunAttemptState = "dispatching" | "running" | "succeeded" | "failed" | "canceled" | "lost";

export type RepositoryRunStepState = "pending" | "running" | "succeeded" | "failed" | "canceled" | "lost" | "skipped";

export type RepositoryRunTerminalReason = { "kind": "step-failed", step_index: number, exit_code: number, } | { "kind": "timed-out", step_index: number | null, } | { "kind": "canceled", step_index: number | null, } | { "kind": "execution-lost", step_index: number | null, } | { "kind": "dispatch-attempts-exhausted" } | { "kind": "runtime-setup-failed", exit_code: number, message: string, };

export type RepositoryRunCacheColdReason = "metadata-missing" | "metadata-invalid" | "metadata-not-ready" | "volume-missing" | "volume-invalid" | "backing-directory-missing";

export type RepositoryRunCachePreparation = { "kind": "exact" } | { "kind": "compatible" } | { "kind": "cold", reason: RepositoryRunCacheColdReason, };

export type RepositoryRunCacheFinalState = "pending" | "ready" | "evicted";

export type RepositoryRunCacheObservationResponse = { workflow_path: string, job_key: string, identity_digest: string, preparation: RepositoryRunCachePreparation, key_ms: number, metadata_ms: number, size_bytes: number, download_verify_ms: number, sync_ms: number, extraction_ms: number, prepare_ms: number, final_state: RepositoryRunCacheFinalState, finalize_ms: number | null, };

export type RepositoryRunCacheSetupObservationResponse = { authorization_ms: number, wall_ms: number, };

export type RepositoryRunCacheResponse = { name: string, path: string, observation: RepositoryRunCacheObservationResponse | null, };

export type RepositoryRunStepResponse = { index: number, name: string, command: string, state: RepositoryRunStepState, started_at_unix: number | null, completed_at_unix: number | null, exit_code: number | null, };

export type RepositoryRunAttemptResponse = { id: string, number: number, external_run_id: string | null, runtime_version: string, state: RepositoryRunAttemptState, created_at_unix: number, started_at_unix: number | null, completed_at_unix: number | null, terminal_reason: RepositoryRunTerminalReason | null, cache_setup: RepositoryRunCacheSetupObservationResponse | null, caches: Array<RepositoryRunCacheResponse>, steps: Array<RepositoryRunStepResponse>, };

export type RepositoryRunWorkflowResponse = { key: string, name: string, path: string, manual: boolean, push_main: boolean, job_count: number, };

export type RepositoryRunWorkflowListResponse = { workflows: Array<RepositoryRunWorkflowResponse>, };

export type RepositoryRunHistoryPageResponse = { runs: Array<RepositoryRunSummaryResponse>, next_cursor: string | null, };

export type RepositoryRunLogResponse = { byte_length: number, position: number, sequence: number, text: string, created_at_unix: number, };

export type RepositoryRunDetailResponse = { run: RepositoryRunSummaryResponse, jobs: Array<RepositoryRunJobDetailResponse>, };

export type RepositoryRunStepLogPageResponse = { logs: Array<RepositoryRunLogResponse>, next_after: number, logs_truncated: boolean, has_earlier: boolean, has_more: boolean, };

export const ApiRouteTemplates = {
  accountSession: "/v1/session",
  cliDeviceLoginComplete: "/v1/cli/device-login/{user_code}/complete",
  cliBrowserLoginComplete: "/v1/cli/browser-login/{request_id}/complete",
  cliExchangeGrants: "/v1/cli/exchange-grants",
  cliSessions: "/v1/cli/sessions",
  cliSessionById: "/v1/cli/sessions/{session_id}",
  repos: "/v1/repos",
  ownerRepositories: "/v1/users/{handle}/repos",
  repo: "/v1/repos/{owner}/{repo}",
  repoConfig: "/v1/repos/{owner}/{repo}/config",
  repoMetadata: "/v1/repos/{owner}/{repo}/metadata",
  repoRunWorkflows: "/v1/repos/{owner}/{repo}/run-workflows",
  repoRuns: "/v1/repos/{owner}/{repo}/runs",
  repoRunDetail: "/v1/repos/{owner}/{repo}/runs/{run_id}/detail",
  repoRunStepLogs: "/v1/repos/{owner}/{repo}/runs/{run_id}/attempts/{attempt_id}/steps/{step_index}/logs",
  repoRunCancel: "/v1/repos/{owner}/{repo}/runs/{run_id}/cancel",
  repoRunRetry: "/v1/repos/{owner}/{repo}/runs/{run_id}/retry",
  repoPushIntents: "/v1/repos/{owner}/{repo}/push-intents",
  repoRequests: "/v1/repos/{owner}/{repo}/requests",
  repoRequestQueue: "/v1/repos/{owner}/{repo}/requests/queue",
  repoRequestAttention: "/v1/repos/{owner}/{repo}/requests/{request_id}/attention",
  repoRequest: "/v1/repos/{owner}/{repo}/requests/{request_id}",
  repoRequestSubmit: "/v1/repos/{owner}/{repo}/requests/{request_id}/submit",
  repoRequestMerge: "/v1/repos/{owner}/{repo}/requests/{request_id}/merge",
  repoRequestRatings: "/v1/repos/{owner}/{repo}/requests/{request_id}/ratings",
  repoRequestInvitees: "/v1/repos/{owner}/{repo}/requests/{request_id}/invitees",
  repoRequestInviteesMe: "/v1/repos/{owner}/{repo}/requests/{request_id}/invitees/me",
  repoRequestAttachments: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments",
  repoRequestAttachmentLimits: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments/limits",
  repoRequestAttachmentPrepare: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments/prepare",
  repoRequestAttachment: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments/{attachment_id}",
  repoRequestAttachmentFinish: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments/{attachment_id}/finish",
  repoRequestAttachmentRetry: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments/{attachment_id}/retry",
  repoRequestAttachmentMediaGrant: "/v1/repos/{owner}/{repo}/requests/{request_id}/attachments/{attachment_id}/media-grant",
  repoSession: "/v1/repos/{owner}/{repo}/session",
  repoFiles: "/v1/repos/{owner}/{repo}/files",
  repoFileContent: "/v1/repos/{owner}/{repo}/files/content",
  repoRequestRevisions: "/v1/repos/{owner}/{repo}/requests/{request_id}/changes",
  repoRequestRevisionCommitFileDiff: "/v1/repos/{owner}/{repo}/requests/{request_id}/changes/{revision_id}/commits/{commit_oid}/file-diff",
  repoRequestDiscussions: "/v1/repos/{owner}/{repo}/requests/{request_id}/timeline",
  repoRequestDiscussionChanges: "/v1/repos/{owner}/{repo}/requests/{request_id}/timeline/changes",
  repoRequestDiscussionReplies: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/replies",
  repoRequestDiscussionResolve: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/resolve",
  repoRequestDiscussionReopen: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/reopen",
  repoRequestDiscussionReopenAndReply: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/reopen-and-reply",
  repoRequestDiscussionRead: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/read",
  repoRequestActivity: "/v1/repos/{owner}/{repo}/requests/{request_id}/activity",
  repoEvents: "/v1/repos/{owner}/{repo}/events",
  repoHistory: "/v1/repos/{owner}/{repo}/history",
  repoHistoryEntry: "/v1/repos/{owner}/{repo}/history/{entry_id}",
  repoHistoryEntryFileDiff: "/v1/repos/{owner}/{repo}/history/{entry_id}/file-diff",
  repoMembers: "/v1/repos/{owner}/{repo}/members",
  repoInvites: "/v1/repos/{owner}/{repo}/invites",
  repoInvite: "/v1/repos/{owner}/{repo}/invites/{invite_id}",
  repoMember: "/v1/repos/{owner}/{repo}/members/{member_user_id}",
  repositoryInvite: "/v1/repository-invites/{token}",
  repositoryInviteAccept: "/v1/repository-invites/{token}/accept",
  repoProjectionPreview: "/v1/repos/{owner}/{repo}/projection-preview",
  gitRepo: "/git/{mode}/{org}/{repo}",
} as const;

export function buildApiPath(
  template: string,
  params: Readonly<Record<string, string>> = {},
): string {
  return template.replace(/\{([^}]+)\}/g, (_match, key: string) => {
    const value = params[key]
    if (value === undefined) throw new Error(`Missing API route parameter: ${key}`)
    return encodeURIComponent(value)
  })
}
