/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as CliLoginRouteImport } from './routes/cli-login'
import { Route as AccountRouteImport } from './routes/account'
import { Route as OwnerRouteImport } from './routes/$owner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/$owner.index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as InvitesTokenRouteImport } from './routes/invites.$token'
import { Route as OwnerRepoRouteImport } from './routes/$owner.$repo'
import { Route as OwnerRepoSettingsRouteImport } from './routes/$owner.$repo.settings'
import { Route as OwnerRepoRunsRouteImport } from './routes/$owner.$repo.runs'
import { Route as OwnerRepoRequestsRouteImport } from './routes/$owner.$repo.requests'
import { Route as OwnerRepoHistoryRouteImport } from './routes/$owner.$repo.history'
import { Route as OwnerRepoCodeRouteImport } from './routes/$owner.$repo._code'
import { Route as OwnerRepoRunsIndexRouteImport } from './routes/$owner.$repo.runs.index'
import { Route as OwnerRepoRequestsIndexRouteImport } from './routes/$owner.$repo.requests.index'
import { Route as OwnerRepoCodeIndexRouteImport } from './routes/$owner.$repo._code.index'
import { Route as OwnerRepoRunsRunIdRouteImport } from './routes/$owner.$repo.runs.$runId'
import { Route as OwnerRepoRequestsRequestIdRouteImport } from './routes/$owner.$repo.requests.$requestId'
import { Route as OwnerRepoRequestsRequestIdIndexRouteImport } from './routes/$owner.$repo.requests.$requestId.index'
import { Route as OwnerRepoRunsWorkflowsWorkflowRouteImport } from './routes/$owner.$repo.runs.workflows.$workflow'
import { Route as OwnerRepoRequestsRequestIdChangesRouteImport } from './routes/$owner.$repo.requests.$requestId.changes'

const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CliLoginRoute = CliLoginRouteImport.update({
  id: '/cli-login',
  path: '/cli-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/$owner',
  path: '/$owner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesTokenRoute = InvitesTokenRouteImport.update({
  id: '/invites/$token',
  path: '/invites/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoRoute = OwnerRepoRouteImport.update({
  id: '/$repo',
  path: '/$repo',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRepoSettingsRoute = OwnerRepoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoRunsRoute = OwnerRepoRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoRequestsRoute = OwnerRepoRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoHistoryRoute = OwnerRepoHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCodeRoute = OwnerRepoCodeRouteImport.update({
  id: '/_code',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoRunsIndexRoute = OwnerRepoRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoRunsRoute,
} as any)
const OwnerRepoRequestsIndexRoute = OwnerRepoRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoRequestsRoute,
} as any)
const OwnerRepoCodeIndexRoute = OwnerRepoCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoCodeRoute,
} as any)
const OwnerRepoRunsRunIdRoute = OwnerRepoRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => OwnerRepoRunsRoute,
} as any)
const OwnerRepoRequestsRequestIdRoute =
  OwnerRepoRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => OwnerRepoRequestsRoute,
  } as any)
const OwnerRepoRequestsRequestIdIndexRoute =
  OwnerRepoRequestsRequestIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OwnerRepoRequestsRequestIdRoute,
  } as any)
const OwnerRepoRunsWorkflowsWorkflowRoute =
  OwnerRepoRunsWorkflowsWorkflowRouteImport.update({
    id: '/workflows/$workflow',
    path: '/workflows/$workflow',
    getParentRoute: () => OwnerRepoRunsRoute,
  } as any)
const OwnerRepoRequestsRequestIdChangesRoute =
  OwnerRepoRequestsRequestIdChangesRouteImport.update({
    id: '/changes',
    path: '/changes',
    getParentRoute: () => OwnerRepoRequestsRequestIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$owner': typeof OwnerRouteWithChildren
  '/account': typeof AccountRoute
  '/cli-login': typeof CliLoginRoute
  '/licenses': typeof LicensesRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/invites/$token': typeof InvitesTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/history': typeof OwnerRepoHistoryRoute
  '/$owner/$repo/requests': typeof OwnerRepoRequestsRouteWithChildren
  '/$owner/$repo/runs': typeof OwnerRepoRunsRouteWithChildren
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/requests/$requestId': typeof OwnerRepoRequestsRequestIdRouteWithChildren
  '/$owner/$repo/runs/$runId': typeof OwnerRepoRunsRunIdRoute
  '/$owner/$repo/': typeof OwnerRepoCodeIndexRoute
  '/$owner/$repo/requests/': typeof OwnerRepoRequestsIndexRoute
  '/$owner/$repo/runs/': typeof OwnerRepoRunsIndexRoute
  '/$owner/$repo/requests/$requestId/changes': typeof OwnerRepoRequestsRequestIdChangesRoute
  '/$owner/$repo/runs/workflows/$workflow': typeof OwnerRepoRunsWorkflowsWorkflowRoute
  '/$owner/$repo/requests/$requestId/': typeof OwnerRepoRequestsRequestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cli-login': typeof CliLoginRoute
  '/licenses': typeof LicensesRoute
  '/$owner/$repo': typeof OwnerRepoCodeIndexRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/$repo/history': typeof OwnerRepoHistoryRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/runs/$runId': typeof OwnerRepoRunsRunIdRoute
  '/$owner/$repo/requests': typeof OwnerRepoRequestsIndexRoute
  '/$owner/$repo/runs': typeof OwnerRepoRunsIndexRoute
  '/$owner/$repo/requests/$requestId/changes': typeof OwnerRepoRequestsRequestIdChangesRoute
  '/$owner/$repo/runs/workflows/$workflow': typeof OwnerRepoRunsWorkflowsWorkflowRoute
  '/$owner/$repo/requests/$requestId': typeof OwnerRepoRequestsRequestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$owner': typeof OwnerRouteWithChildren
  '/account': typeof AccountRoute
  '/cli-login': typeof CliLoginRoute
  '/licenses': typeof LicensesRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/invites/$token': typeof InvitesTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/_code': typeof OwnerRepoCodeRouteWithChildren
  '/$owner/$repo/history': typeof OwnerRepoHistoryRoute
  '/$owner/$repo/requests': typeof OwnerRepoRequestsRouteWithChildren
  '/$owner/$repo/runs': typeof OwnerRepoRunsRouteWithChildren
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/requests/$requestId': typeof OwnerRepoRequestsRequestIdRouteWithChildren
  '/$owner/$repo/runs/$runId': typeof OwnerRepoRunsRunIdRoute
  '/$owner/$repo/_code/': typeof OwnerRepoCodeIndexRoute
  '/$owner/$repo/requests/': typeof OwnerRepoRequestsIndexRoute
  '/$owner/$repo/runs/': typeof OwnerRepoRunsIndexRoute
  '/$owner/$repo/requests/$requestId/changes': typeof OwnerRepoRequestsRequestIdChangesRoute
  '/$owner/$repo/runs/workflows/$workflow': typeof OwnerRepoRunsWorkflowsWorkflowRoute
  '/$owner/$repo/requests/$requestId/': typeof OwnerRepoRequestsRequestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$owner'
    | '/account'
    | '/cli-login'
    | '/licenses'
    | '/$owner/$repo'
    | '/invites/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$owner/'
    | '/$owner/$repo/history'
    | '/$owner/$repo/requests'
    | '/$owner/$repo/runs'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/requests/$requestId'
    | '/$owner/$repo/runs/$runId'
    | '/$owner/$repo/'
    | '/$owner/$repo/requests/'
    | '/$owner/$repo/runs/'
    | '/$owner/$repo/requests/$requestId/changes'
    | '/$owner/$repo/runs/workflows/$workflow'
    | '/$owner/$repo/requests/$requestId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cli-login'
    | '/licenses'
    | '/$owner/$repo'
    | '/invites/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$owner'
    | '/$owner/$repo/history'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/runs/$runId'
    | '/$owner/$repo/requests'
    | '/$owner/$repo/runs'
    | '/$owner/$repo/requests/$requestId/changes'
    | '/$owner/$repo/runs/workflows/$workflow'
    | '/$owner/$repo/requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/$owner'
    | '/account'
    | '/cli-login'
    | '/licenses'
    | '/$owner/$repo'
    | '/invites/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$owner/'
    | '/$owner/$repo/_code'
    | '/$owner/$repo/history'
    | '/$owner/$repo/requests'
    | '/$owner/$repo/runs'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/requests/$requestId'
    | '/$owner/$repo/runs/$runId'
    | '/$owner/$repo/_code/'
    | '/$owner/$repo/requests/'
    | '/$owner/$repo/runs/'
    | '/$owner/$repo/requests/$requestId/changes'
    | '/$owner/$repo/runs/workflows/$workflow'
    | '/$owner/$repo/requests/$requestId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  AccountRoute: typeof AccountRoute
  CliLoginRoute: typeof CliLoginRoute
  LicensesRoute: typeof LicensesRoute
  InvitesTokenRoute: typeof InvitesTokenRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-login': {
      id: '/cli-login'
      path: '/cli-login'
      fullPath: '/cli-login'
      preLoaderRoute: typeof CliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner': {
      id: '/$owner'
      path: '/$owner'
      fullPath: '/$owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/': {
      id: '/$owner/'
      path: '/'
      fullPath: '/$owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$token': {
      id: '/invites/$token'
      path: '/invites/$token'
      fullPath: '/invites/$token'
      preLoaderRoute: typeof InvitesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo': {
      id: '/$owner/$repo'
      path: '/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/$owner/$repo/settings': {
      id: '/$owner/$repo/settings'
      path: '/settings'
      fullPath: '/$owner/$repo/settings'
      preLoaderRoute: typeof OwnerRepoSettingsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/runs': {
      id: '/$owner/$repo/runs'
      path: '/runs'
      fullPath: '/$owner/$repo/runs'
      preLoaderRoute: typeof OwnerRepoRunsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/requests': {
      id: '/$owner/$repo/requests'
      path: '/requests'
      fullPath: '/$owner/$repo/requests'
      preLoaderRoute: typeof OwnerRepoRequestsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/history': {
      id: '/$owner/$repo/history'
      path: '/history'
      fullPath: '/$owner/$repo/history'
      preLoaderRoute: typeof OwnerRepoHistoryRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/_code': {
      id: '/$owner/$repo/_code'
      path: ''
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoCodeRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/runs/': {
      id: '/$owner/$repo/runs/'
      path: '/'
      fullPath: '/$owner/$repo/runs/'
      preLoaderRoute: typeof OwnerRepoRunsIndexRouteImport
      parentRoute: typeof OwnerRepoRunsRoute
    }
    '/$owner/$repo/requests/': {
      id: '/$owner/$repo/requests/'
      path: '/'
      fullPath: '/$owner/$repo/requests/'
      preLoaderRoute: typeof OwnerRepoRequestsIndexRouteImport
      parentRoute: typeof OwnerRepoRequestsRoute
    }
    '/$owner/$repo/_code/': {
      id: '/$owner/$repo/_code/'
      path: '/'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoCodeIndexRouteImport
      parentRoute: typeof OwnerRepoCodeRoute
    }
    '/$owner/$repo/runs/$runId': {
      id: '/$owner/$repo/runs/$runId'
      path: '/$runId'
      fullPath: '/$owner/$repo/runs/$runId'
      preLoaderRoute: typeof OwnerRepoRunsRunIdRouteImport
      parentRoute: typeof OwnerRepoRunsRoute
    }
    '/$owner/$repo/requests/$requestId': {
      id: '/$owner/$repo/requests/$requestId'
      path: '/$requestId'
      fullPath: '/$owner/$repo/requests/$requestId'
      preLoaderRoute: typeof OwnerRepoRequestsRequestIdRouteImport
      parentRoute: typeof OwnerRepoRequestsRoute
    }
    '/$owner/$repo/requests/$requestId/': {
      id: '/$owner/$repo/requests/$requestId/'
      path: '/'
      fullPath: '/$owner/$repo/requests/$requestId/'
      preLoaderRoute: typeof OwnerRepoRequestsRequestIdIndexRouteImport
      parentRoute: typeof OwnerRepoRequestsRequestIdRoute
    }
    '/$owner/$repo/runs/workflows/$workflow': {
      id: '/$owner/$repo/runs/workflows/$workflow'
      path: '/workflows/$workflow'
      fullPath: '/$owner/$repo/runs/workflows/$workflow'
      preLoaderRoute: typeof OwnerRepoRunsWorkflowsWorkflowRouteImport
      parentRoute: typeof OwnerRepoRunsRoute
    }
    '/$owner/$repo/requests/$requestId/changes': {
      id: '/$owner/$repo/requests/$requestId/changes'
      path: '/changes'
      fullPath: '/$owner/$repo/requests/$requestId/changes'
      preLoaderRoute: typeof OwnerRepoRequestsRequestIdChangesRouteImport
      parentRoute: typeof OwnerRepoRequestsRequestIdRoute
    }
  }
}

interface OwnerRepoCodeRouteChildren {
  OwnerRepoCodeIndexRoute: typeof OwnerRepoCodeIndexRoute
}

const OwnerRepoCodeRouteChildren: OwnerRepoCodeRouteChildren = {
  OwnerRepoCodeIndexRoute: OwnerRepoCodeIndexRoute,
}

const OwnerRepoCodeRouteWithChildren = OwnerRepoCodeRoute._addFileChildren(
  OwnerRepoCodeRouteChildren,
)

interface OwnerRepoRequestsRequestIdRouteChildren {
  OwnerRepoRequestsRequestIdChangesRoute: typeof OwnerRepoRequestsRequestIdChangesRoute
  OwnerRepoRequestsRequestIdIndexRoute: typeof OwnerRepoRequestsRequestIdIndexRoute
}

const OwnerRepoRequestsRequestIdRouteChildren: OwnerRepoRequestsRequestIdRouteChildren =
  {
    OwnerRepoRequestsRequestIdChangesRoute:
      OwnerRepoRequestsRequestIdChangesRoute,
    OwnerRepoRequestsRequestIdIndexRoute: OwnerRepoRequestsRequestIdIndexRoute,
  }

const OwnerRepoRequestsRequestIdRouteWithChildren =
  OwnerRepoRequestsRequestIdRoute._addFileChildren(
    OwnerRepoRequestsRequestIdRouteChildren,
  )

interface OwnerRepoRequestsRouteChildren {
  OwnerRepoRequestsRequestIdRoute: typeof OwnerRepoRequestsRequestIdRouteWithChildren
  OwnerRepoRequestsIndexRoute: typeof OwnerRepoRequestsIndexRoute
}

const OwnerRepoRequestsRouteChildren: OwnerRepoRequestsRouteChildren = {
  OwnerRepoRequestsRequestIdRoute: OwnerRepoRequestsRequestIdRouteWithChildren,
  OwnerRepoRequestsIndexRoute: OwnerRepoRequestsIndexRoute,
}

const OwnerRepoRequestsRouteWithChildren =
  OwnerRepoRequestsRoute._addFileChildren(OwnerRepoRequestsRouteChildren)

interface OwnerRepoRunsRouteChildren {
  OwnerRepoRunsRunIdRoute: typeof OwnerRepoRunsRunIdRoute
  OwnerRepoRunsIndexRoute: typeof OwnerRepoRunsIndexRoute
  OwnerRepoRunsWorkflowsWorkflowRoute: typeof OwnerRepoRunsWorkflowsWorkflowRoute
}

const OwnerRepoRunsRouteChildren: OwnerRepoRunsRouteChildren = {
  OwnerRepoRunsRunIdRoute: OwnerRepoRunsRunIdRoute,
  OwnerRepoRunsIndexRoute: OwnerRepoRunsIndexRoute,
  OwnerRepoRunsWorkflowsWorkflowRoute: OwnerRepoRunsWorkflowsWorkflowRoute,
}

const OwnerRepoRunsRouteWithChildren = OwnerRepoRunsRoute._addFileChildren(
  OwnerRepoRunsRouteChildren,
)

interface OwnerRepoRouteChildren {
  OwnerRepoCodeRoute: typeof OwnerRepoCodeRouteWithChildren
  OwnerRepoHistoryRoute: typeof OwnerRepoHistoryRoute
  OwnerRepoRequestsRoute: typeof OwnerRepoRequestsRouteWithChildren
  OwnerRepoRunsRoute: typeof OwnerRepoRunsRouteWithChildren
  OwnerRepoSettingsRoute: typeof OwnerRepoSettingsRoute
}

const OwnerRepoRouteChildren: OwnerRepoRouteChildren = {
  OwnerRepoCodeRoute: OwnerRepoCodeRouteWithChildren,
  OwnerRepoHistoryRoute: OwnerRepoHistoryRoute,
  OwnerRepoRequestsRoute: OwnerRepoRequestsRouteWithChildren,
  OwnerRepoRunsRoute: OwnerRepoRunsRouteWithChildren,
  OwnerRepoSettingsRoute: OwnerRepoSettingsRoute,
}

const OwnerRepoRouteWithChildren = OwnerRepoRoute._addFileChildren(
  OwnerRepoRouteChildren,
)

interface OwnerRouteChildren {
  OwnerRepoRoute: typeof OwnerRepoRouteWithChildren
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerRepoRoute: OwnerRepoRouteWithChildren,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRoute: OwnerRouteWithChildren,
  AccountRoute: AccountRoute,
  CliLoginRoute: CliLoginRoute,
  LicensesRoute: LicensesRoute,
  InvitesTokenRoute: InvitesTokenRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
