minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@tanstack/charts@1.0.0'
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
blockExoticSubdeps: true
overrides:
  lodash-es: 4.18.1
  source-map-js: 1.2.2
supportedArchitectures:
  os:
    - current
    - linux
    - win32
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
allowBuilds:
  bufferutil: false
  core-js: false
  utf-8-validate: false
